.TH PCE-RC759 1 "2012-07-08" "HH" "pce"
\
.SH NAME
pce-rc759 \- RC759 Piccoline emulator
\
.SH SYNOPSIS
.BI pce-rc759 " [options]"
\
.SH DESCRIPTION
.BR pce-759 (1)
is an RC759 Piccoline emulator.
\
.SH OPTIONS
.TP
.BI "-c, --config " file
Set the config file name.
\
.TP
.BI "-d, --path " string
Add a directory to the search path.

The search path is used if an input file (such as a ROM
image or a disk image) is specified with a relative file
name. In that case the file is searched for in all
directories of the search path. The current directory
is always implicitly added to the end of the search path.

The directory name can be prefixed by one of these characters:
.RS
.TP
.B +
Add the directory to the end of the search path
.TP
.B -
Add the directory to the beginning of the search path
.TP
.B =
Clear the search path before adding the directory
.RE

.IP
The default is to add the directory to the end of the search path.
\
.TP
.BI "-g, --video " string
Set the video type to either \fBcolor\fR or \fBmono\fR.
\
.TP
.BI "-l, --log " file
Write log messages to the file specified instead of stdout.
\
.TP
.B "-q, --quiet"
Don't print anything to stdout or stderr.
\
.TP
.B "-r, --run"
Start running immediately.
\
.TP
.B "-R, --no-monitor"
Start running immediately and never fall back to the monitor.
This is useful if stdout is not visible, for example because
the emulator was started directly from a graphical user
interface such as X or Windows.
\
.TP
.BI "-s, --speed" factor
Set the initial speed factor. This overrides a value specified
in the configuration file.
\
.TP
.BI "-t, --terminal " string
Set the terminal device. Possible devices are
.BR null ", "
.BR x11 " and "
.BR sdl "."
\
.TP
.B "-v, --verbose"
Verbose operation. This is highly recommended.
\
.TP
.B --help
Print usage information
\
.TP
.B --version
Print version information
\
.SH SEE ALSO
.BR cpmtools (1)
\
.SH AUTHOR
Hampa Hug <hampa@hampa.ch>
