.TH PCE 1 "2004-01-09" "HH" "pce"
\
.SH NAME
pce \- IBM PC emulator
\
.SH SYNOPSIS
.BI pce " [options]"
.PP
.BI pce " --help"
.PP
.BI pce " --version"
\
.SH DESCRIPTION
.BR pce (1)
is an IBM PC hardware emulator. It emulates most of
the hardware of an IBM PC 5150. The emulation is complete enough to
boot DOS and run most DOS applications.
\
.SH OPTIONS
.TP
.B --help
Print usage information
\
.TP
.B --version
Print version information
\
.TP
.BI "-b, --boot " drive
Set the boot drive. Default is 128.
\
.TP
.BI "-c, --config " file
Set the config file name.
\
.TP
.BI "-g, --video " string
Set the video device. Possible devices are
.BR mda ", "
.BR cga ", "
.BR hgc " and "
.BR ega "."
\
.TP
.BI "-t, --terminal " string
Set the terminal device. Possible devices are
.BR null ", "
.BR vt100 ", "
.BR x11 " and "
.BR sdl "."
\
.TP
.BI "-p, --cpu " model
Select the CPU model to be emulated. Possible values are
.BR 8086 ", "
.BR 8088 ", "
.BR 80186 ", "
.BR 80188 ", "
.BR v20 " and "
.BR v30 "."
This overrides the cpu model specified in the config file.
\
.TP
.B "-v, --verbose"
Verbose operation. This is highly recommended.
\
.TP
.BI "-l, --log " file
Write log messages to the file specified instead of stdout.
\
.TP
.B "-r, --run"
Start running immediately
\
.SH SEE ALSO
.BR bochs "(1), " mtools (1)
\
.SH AUTHOR
Hampa Hug <hampa@hampa.ch>
