.TH AYM 1 "2015-05-21" "HH" "pce"
\
.SH NAME
aym \- convert and play AYM sound files

.SH SYNOPSIS
.BI aym " [options] [input-file output-file]]"

.SH DESCRIPTION
\fBaym\fR(1) is used to convert and play AYM sound files.

.SH OPTIONS
.TP
.BI "-i, --input " filename
Load an image from \fIfilename\fR.
\
.TP
.BI "-o, --output " filename
Set the output file name. Before exiting, the current image will
be written to this file.
\
.TP
.B "-v, --verbose"
Enable verbose operation.
\
.TP
.B --help
Print usage information.
\
.TP
.B --version
Print version information.

.SH SEE ALSO
.BR pce-atarist "(1)"

.SH AUTHOR
Hampa Hug <hampa@hampa.ch>
